[package]
name = "harness-primitives"
version = "0.1.0"
edition = "2021"
authors = ["Osoro Bironga <fanosoro@gmail.com>"]

[dependencies]
anyhow = "1.0.82"
serde = "1.0.198"
serde_json = "1.0.116"
thiserror = "1.0.59"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
syn = { version = "2" }
proc-macro2 = { version = "1", default-features = false }
quote = "1.0.7"
wapc = "1.1.0"
wasmtime-provider = "1.16.0"
candid_parser = "0.1.4"
candid = "0.10.8"
