[package]
name = "harness-primitives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
serde = "1.0.198"
serde_json = "1.0.116"
thiserror = "1.0.59"
syn = { version = "2" }
proc-macro2 = { version = "1", default-features = false }
quote = "1.0.7"
