[package]
name = "hello"
version = "0.1.0"
edition = "2021"
authors = ["Osoro Bironga <fanosoro@gmail.com>"]
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
harness-cdk = { path = "../../harness-cdk" }

[features]
__harness-build = ["harness-cdk/__harness-build"]
